

server:
  port: 2003

eureka:
  instance:
    hostname: eureka3.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1.com:2001/eureka/,http://eureka2.com:2002/eureka/
